language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
env:
 matrix:
 - DOCKER_IMAGE=les10taakdestinationservice
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build 
- docker push $DOCKER_IMAGE